# Generated by Django 4.0.4 on 2022-07-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_fiat_comision_fiatt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comision',
            new_name='Comisions',
        ),
        migrations.RenameField(
            model_name='comisions',
            old_name='fiatt',
            new_name='fiat',
        ),
    ]
